services:
  - type: web
    name: school-backend
    env: docker

    buildCommand: ""

    startCommand: ""

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false