name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Composer
        run: composer install --no-dev --optimize-autoloader
        working-directory: school-backend

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Vue
        run: npm install
        working-directory: school-frontend

      - name: Build Vue
        run: npm run build
        working-directory: school-frontend

      - name: Upload Website
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /htdocs/
          # --- ADDED TIMEOUT CONFIGURATION ---
          timeout: 600000        # Sets the timeout threshold to 10 minutes (600k ms)